### ISSUE TITLE
Can OpenAstro integrate with a webpage ?

### ISSUE THREAD

**Issue by pratik28** [raininja/openastro#1]
Hello,
I need to show a natal chart on a PHP webpage and was searching for open source software to do that.
Can your OpenAstro package or a function within it, be called from a PHP script( webpage) to get a natal chart image in return?
Thanks
Pratik

**Comment by raininja** [comment]
Hello, 

Sorry for the delay. there isn't an API or daemon functionality, it's a standalone program without anything RESTy (yet), but here is a link to a [github search that may help you ](https://github.com/topics/horoscope-api)
