### ISSUE TITLE
Will there be an update for Python 3.11?

### ISSUE THREAD

**Issue by teledyn** [raininja/openastro#2]
Mostly just checking to see if you might be planning an update as the code comments suggest openAstroCfg has been moved into configuration, and both moved into openastromod, but code references appear to fail as these are not prefixed with the package and many spots still reference the old openAstroCfg.py. Also, the swisseph package is listed in pip, but the package is empty.

So the whole thing looks very inviting, but I'm unable to get it running on Ubuntu 23.04, and really hoping it is fixable!

**Comment by raininja** [comment]
Hey, I'm working on updating it, it's not ready to run yet! Thanks for looking, I should have some results soon.

**Comment by teledyn** [comment]
Excellent news! Thank you!  If there's anything you'd like me to test, just ask! :)
